pipeline {
  agent any
  tools { nodejs 'NodeJS_25' }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install dependencies') {
      steps {
        dir('tests') {
          sh 'npm ci'
          sh 'npx playwright install --with-deps'
        }
      }
    }

    stage('Run Playwright tests') {
      steps {
        dir('tests') {
          sh 'npx playwright test --reporter=html --output=playwright-report'
        }
      }
    }
  }

  post {
    always {
      publishHTML(target: [
        reportDir: 'playwright-report',
        reportFiles: 'index.html',
        reportName: 'Playwright Test Tester Report',
        keepAll: true,
        alwaysLinkToLastBuild: true
      ])
    }
  }
}
